[package]
name = "gpu_life"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.19" # Or latest version
winit = "0.29" # Or latest version
env_logger = "0.11"
pollster = "0.3"
bytemuck = { version = "1.15", features = ["derive"] }
log = "0.4" 